version: "3"
services:

  actinia:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    #volumes:
      # uncomment to mount grass-gis-addons etc while developing:
      # - ../processing/scripts:/src/processing/scripts
      # - ../processing/input:/src/input
      # - ../grass-gis-addons:/src/grass-gis-addons
      
    environment:
      ACTINIA_USER: ${ACTINIA_USER}
      ACTINIA_PW: ${ACTINIA_PW}
      EODAG_USER: ${EODAG_USER}
      EODAG_PW: ${EODAG_PW}
    ports:
      - "8088:8088"
    depends_on:
      - valkey

  valkey:
    image: valkey/valkey:8.1-alpine
    volumes:
      - ./valkey_data:/data
    environment:
      - VALKEY_PASS_FILE=/data/config/.valkey
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/valkey.conf"
      --requirepass "$$(cat $$VALKEY_PASS_FILE)"
      '
    ]