---
name: Linting and code quality check

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    uses: mundialis/github-workflows/.github/workflows/linting.yml@exclude_option_for_json_linting
    with:
      FILTER_REGEX_EXCLUDE: ".*processing/templates/template_MAIN_loop.json"